import os
import json
import time
import random
import logging
from pathlib import Path
from typing import Dict, List, Optional, Any
import requests
from bs4 import BeautifulSoup
import feedparser
from tenacity import retry, wait_exponential, stop_after_attempt, retry_if_exception_type

logging.basicConfig(
    level=logging.INFO, 
    format='%(asctime)s - [%(levelname)s] - %(name)s - %(message)s'
)
logger = logging.getLogger("MultimodalScraper")

# Pool of User-Agents to prevent basic rate-limiting/blocking from news sites
USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0"
]

class MultimodalNewsScraper:
    """
    Production scraper that uses heuristic keywords to discover regional news articles,
    extracting paired visual (image URLs) and textual (descriptions) data.
    """
    
    def __init__(self, heuristics_path: str = "../../data/intermediate/twb_heuristic_keywords.json", 
                 output_dir: str = "../../data/raw"):
        self.heuristics_file = Path(heuristics_path)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.output_file = self.output_dir / "multimodal_news_scrape.jsonl"
        
        if not self.heuristics_file.exists():
            raise FileNotFoundError(f"Heuristics file missing at {self.heuristics_file}. Run twb_glossary.py first.")
            
        self.session = requests.Session()

    def _get_headers(self) -> Dict[str, str]:
        """Returns headers with a randomized User-Agent."""
        return {"User-Agent": random.choice(USER_AGENTS)}

    def load_heuristics(self) -> Dict[str, List[str]]:
        """Loads the localized terminology generated by the TWB ingestor."""
        logger.info(f"Loading heuristic keywords from {self.heuristics_file}")
        with open(self.heuristics_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data.get("keywords", {})

    def discover_articles_via_rss(self, keyword: str, language_code: str) -> List[str]:
        """
        Uses Google News RSS as a discovery mechanism to find recent, 
        relevant articles in the target language containing the heuristic keyword.
        """
        # hl=language, gl=country (generic representation), q=keyword
        rss_url = f"https://news.google.com/rss/search?q={keyword}&hl={language_code}&gl=US&ceid=US:{language_code}"
        logger.info(f"Discovering articles for keyword: '{keyword}' (Lang: {language_code})")
        
        feed = feedparser.parse(rss_url)
        article_urls = []
        
        # Limit to top 15 results per keyword to manage scope during the hackathon
        for entry in feed.entries[:15]:
            article_urls.append(entry.link)
            
        return article_urls

    @retry(
        wait=wait_exponential(multiplier=1, min=2, max=10),
        stop=stop_after_attempt(3),
        retry=retry_if_exception_type(requests.exceptions.RequestException)
    )
    def scrape_article_data(self, url: str, language: str) -> Optional[Dict[str, Any]]:
        """
        Scrapes the target article to extract the main image (OpenGraph) 
        and surrounding descriptive text.
        """
        try:
            response = self.session.get(url, headers=self._get_headers(), timeout=10)
            response.raise_for_status()
        except requests.exceptions.RequestException as e:
            logger.warning(f"Failed to fetch {url}: {e}")
            return None

        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Extract OpenGraph metadata which reliably pairs standard images with summaries
        og_image = soup.find("meta", property="og:image")
        og_desc = soup.find("meta", property="og:description")
        og_title = soup.find("meta", property="og:title")
        
        if not og_image or not og_desc:
            return None # Skip articles that don't have clear multimodal pairings
            
        return {
            "source_url": url,
            "language_inferred": language,
            "content": og_desc.get("content", ""),
            "title": og_title.get("content", "") if og_title else "",
            "media_urls": [og_image.get("content", "")],
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        }

    def execute_pipeline(self):
        """Runs the end-to-end multimodal scraping pipeline."""
        heuristics = self.load_heuristics()
        total_extracted = 0
        
        logger.info(f"Starting Multimodal scrape. Outputting to {self.output_file}")
        
        with open(self.output_file, 'a', encoding='utf-8') as f:
            for lang, keywords in heuristics.items():
                for keyword in keywords:
                    article_urls = self.discover_articles_via_rss(keyword, lang)
                    
                    for url in article_urls:
                        data = self.scrape_article_data(url, lang)
                        if data:
                            f.write(json.dumps(data, ensure_ascii=False) + '\n')
                            total_extracted += 1
                            
                        # Polite crawling delay to prevent IP bans
                        time.sleep(random.uniform(1.0, 2.5))
                        
        logger.info(f"Multimodal acquisition complete. Extracted {total_extracted} viable text-image pairs.")

if __name__ == "__main__":
    scraper = MultimodalNewsScraper()
    scraper.execute_pipeline()